### ISSUE TITLE
Displaying index.html with assets folder

### ISSUE THREAD

**Issue by Aethelflaed** [mmkal/artifact.ci#8]
Hi
First of all, thanks for your work

I've got a Ruby on Rails application that generates a coverage report using [simplecov](https://github.com/simplecov-ruby/simplecov). It creates a `coverage/` folder with [this](https://gist.github.com/Aethelflaed/efcc9ee33ef57cdb652ec98127b59712) content plus a few hidden json files (that are not uploaded).

I'm using the following to upload the folder:
```yml
      - name: Upload final coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage
```

The coverage gets uploaded correctly (the content linked above is actually from an artefact I downloaded), but artifact.ci fails and tells me:

> content-type header is text/plain, so can't parse as application/json

![Image](https://github.com/user-attachments/assets/ad2eddf9-7897-45be-bb1d-4e1b599ec5a6)

Am I missing a configuration step? What am I doing wrong?

Thanks :)
